CREATE LOGIN [IIS APPPOOL\sWebApi] FROM WINDOWS;
USE shopeefood_db;
CREATE USER [IIS APPPOOL\sWebApi] FOR LOGIN [IIS APPPOOL\sWebApi];
ALTER ROLE db_datareader ADD MEMBER [IIS APPPOOL\sWebApi];
ALTER ROLE db_datawriter ADD MEMBER [IIS APPPOOL\sWebApi];

GRANT EXECUTE TO [IIS APPPOOL\sWebApi];
